import { Skill } from "@/lib/types";
import { commitSkill } from "./commit";
import { prSkill } from "./pr";
import { reviewSkill } from "./review";
import { superpowersSkill } from "./superpowers";
import { contextEngineeringSkill } from "./context-engineering";
import { webAssetGeneratorSkill } from "./web-asset-generator";
import { iosSimulatorSkill } from "./ios-simulator";
import { playwrightSkill } from "./playwright-skill";
import { mcpBuilderSkill } from "./mcp-builder";
import { youtubeTranscriptSkill } from "./youtube-transcript";
import { d3jsVisualizationSkill } from "./d3js-visualization";
import { architectureDiagramSkill } from "./architecture-diagram";
import { apiDocsSkill } from "./api-docs";
import { migrateDbSkill } from "./migrate-db";
import { claudeApiSkill } from "./claude-api";
import { refactorSkill } from "./refactor";
import { testGenSkill } from "./test-gen";
import { changelogSkill } from "./changelog";
import { depsAuditSkill } from "./deps-audit";
// Additional skills
import { securityAuditSkill } from "./security-audit";
import { dockerComposeSkill } from "./docker-compose";
import { perfBenchmarkSkill } from "./perf-benchmark";
import { gitBisectSkill } from "./git-bisect";
import { vibeCodeSkill } from "./vibe-code";
import { monorepoManagerSkill } from "./monorepo-manager";
import { regexBuilderSkill } from "./regex-builder";
import { envSetupSkill } from "./env-setup";
import { codeWalkthroughSkill } from "./code-walkthrough";
import { sqlOptimizerSkill } from "./sql-optimizer";
import { skyvernSkill } from "./skyvern-skill";
// Official Anthropic skills
import { skillCreatorSkill } from "./skill-creator";
import { pdfSkill } from "./pdf";
import { pptxSkill } from "./pptx";
import { xlsxSkill } from "./xlsx";
import { docxSkill } from "./docx";
import { consolidateMemorySkill } from "./consolidate-memory";
import { webappTestingSkill } from "./webapp-testing";

const curatedSkills: Skill[] = [
  sqlOptimizerSkill,
  commitSkill,
  prSkill,
  reviewSkill,
  superpowersSkill,
  contextEngineeringSkill,
  webAssetGeneratorSkill,
  // New community skills
  playwrightSkill,
  mcpBuilderSkill,
  iosSimulatorSkill,
  youtubeTranscriptSkill,
  d3jsVisualizationSkill,
  architectureDiagramSkill,
  apiDocsSkill,
  migrateDbSkill,
  claudeApiSkill,
  // New community skills
  refactorSkill,
  testGenSkill,
  changelogSkill,
  depsAuditSkill,
  // Additional skills
  securityAuditSkill,
  dockerComposeSkill,
  perfBenchmarkSkill,
  gitBisectSkill,
  vibeCodeSkill,
  monorepoManagerSkill,
  regexBuilderSkill,
  envSetupSkill,
  codeWalkthroughSkill,
  skyvernSkill,
  // Official Anthropic skills
  skillCreatorSkill,
  pdfSkill,
  pptxSkill,
  xlsxSkill,
  docxSkill,
  consolidateMemorySkill,
  webappTestingSkill,
];

// Auto-ingested skills from repos containing SKILL.md files.
// Generated by `scripts/ingest/skills.mjs`. Curated entries above always win
// on slug collision.
import ingestedSkillsRaw from "@/data/_ingested/skills.json";

const curatedSkillSlugs = new Set(curatedSkills.map((s) => s.slug));
const ingestedSkills: Skill[] = (ingestedSkillsRaw as unknown as Skill[]).filter(
  (s) => s && s.slug && !curatedSkillSlugs.has(s.slug),
);

export const skills: Skill[] = [...curatedSkills, ...ingestedSkills];

export function getSkillBySlug(slug: string): Skill | undefined {
  return skills.find((s) => s.slug === slug);
}

export function getFeaturedSkills(): Skill[] {
  return skills.filter((s) => s.featured);
}

export function getSkillsByTag(tag: string): Skill[] {
  return skills.filter((s) => s.tags.includes(tag));
}

export function getAllSkillTags(): string[] {
  const tags = new Set<string>();
  skills.forEach((s) => s.tags.forEach((t) => tags.add(t)));
  return Array.from(tags).sort();
}
